### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by noobermin** [OfflineIMAP/imapfw#21]
n/t.

**Comment by mgree** [comment]
It certainly doesn't seem that way. As a reluctant Outlook user, I really wish we had better CLI tools to support modern auth over IMAP. 😭

**Comment by nicolas33** [comment]
This project is dead. I might work on a CLI IMAP client one day but it's not for tomorrow.
You might like to give a try to [offlineimap3](https://github.com/OfflineIMAP/offlineimap3).

**Comment by posita** [comment]
Please [archive the project](https://docs.github.com/en/repositories/archiving-a-github-repository) to signal its status.
