### ISSUE TITLE
configure DNS for imapfw documentation

### ISSUE THREAD

**Issue by nicolas33** [OfflineIMAP/imapfw#5]
@spaetz Could you please set the record `imapfwdoc.offlineimap.org` to a CNAME with url `www.gitbooks.io`.

Notice this is not for github but gitbook.

More details [here](https://help.gitbook.com/platform/domains.html).

**Comment by spaetz** [comment]
Done, it might take a while to propagate. Please close when it works.

**Comment by nicolas33** [comment]
Thank you much!
