### ISSUE TITLE
IMAP timeout not configurable

### ISSUE THREAD

**Issue by ml31415** [OfflineIMAP/imapfw#8]
Given this BT: 

<pre>
CRITICAL: Account.0.Driver.0 unhandled error occurred while reacting to event ('connect', (), {}): abort: IMAP4 protocol error: no response after 2 secs
ERROR   : IMAP4 protocol error: no response after 2 secs
Traceback (most recent call last):
  File "/home/michael/workspace/imapfw/imapfw/edmp.py", line 404, in react
    self._cache[topic] = self._react(topic, args, kwargs)
  File "/home/michael/workspace/imapfw/imapfw/edmp.py", line 382, in _react
    return func(*args, **kwargs)
  File "/home/michael/workspace/imapfw/imapfw/drivers/imap.py", line 31, in connect
    return self.imap.connect(host, port)
  File "/home/michael/workspace/imapfw/imapfw/imap/imap.py", line 125, in connect
    self.imap = imaplib2.IMAP4(host, port, debug=3, timeout=2)
  File "/home/michael/workspace/imapfw/imapfw/imap/imaplib3/imaplib2.py", line 372, in __init__
    self.welcome = self._request_push(name='welcome', tag='continuation').get_response('IMAP4 protocol error: %s')[1]
  File "/home/michael/workspace/imapfw/imapfw/imap/imaplib3/imaplib2.py", line 188, in get_response
    raise typ(exc_fmt % str(val))
imapfw.imap.imaplib3.imaplib2.abort: IMAP4 protocol error: no response after 2 secs
</pre>

It would be nice to be able to set this on a per-connection level in the rascal file. And in any case, two seconds seem to be really short. I guess a sane default would be at least 10 seconds, probably even 30.

**Comment by nicolas33** [comment]
Yes. I'm using short delays to fail fast while hacking on imapfw. Exposing this setting at some point is still a TODO.

We have more important work underway, for now. :-)

**Comment by ml31415** [comment]
Allright with the priority, but why closing this issue then, instead of keeping it as a reminder for the TODO?

**Comment by nicolas33** [comment]
This issue is pertinent. I have a lot of things in mind and I'm in the way of sharing them with new contributors. I don't want issues to become our next TODO list.

**Comment by nicolas33** [comment]
We recently moved the TODO to the public writable wiki. I've added [your items to the list](https://github.com/OfflineIMAP/imapfw/wiki/TODO#rascal).

Thank you for the reports!
