### ISSUE TITLE
Sane defaults for rascal files

### ISSUE THREAD

**Issue by ml31415** [OfflineIMAP/imapfw#9]
This seems to be the minimal rascal file to get some simple IMAP sync going on:

``` python
from imapfw.api import engines, types, drivers
MainConf = {'max_sync_accounts': 1}

def configure(ui):
    pass

class ImapLeft(types.Imap):
    conf = dict(backend='imaplib3',
                host='mail.your-server.de',
                port='993',
                username='username1',
                password='password1')
    driver = drivers.Imap

class ImapRight(types.Imap):
    conf = dict(backend='imaplib3',
                host='mail.your-server.de',
                port='993',
                username='username2',
                password='password2')
    driver = drivers.Imap

class MainAccount(types.Account):
    left = ImapLeft
    right = ImapRight
```

For a simple config file this is an insane amount of verboseness. Why do I need to define `configure`, if it's totally fine if it doesn't do anything? Why is there no default-`configure`, if none is provided in the rascal file? Why do I need to set `MainConf`, if the number of useful processes could perfectly be autodetected, if not provided in the config? Why do I need to specify any backend, if `imaplib3` seems to be a sane default for any subclass of `types.Imap`? Why define a driver, if `drivers.Imap` is again a sane default?

For the sake of making something actually useful for enduser out of this project, please, provide some sane defaults! I'd also like to suggest to provide an alternative way of configuration using simple yaml files, for anyone who just wants to use the program for simple syncs, without any intention to write programs with it.

**Comment by nicolas33** [comment]
> For a simple config file this is an insane amount of verboseness.

Please, understand that imapfw is in early stage of development.

> Why do I need to define [...]

Enabling defaults will come later.

> I'd also like to suggest to provide an alternative way of configuration using simple yaml files, for anyone who just wants to use the program for simple syncs, without any intention to write programs with it.

I don't think I'll support YAML. There is already code to map code to dictionnaries. So, the settings for configuration could be written as a dict.

However, I'm fine by merging YAML support. For now, this is still premature, though.

You're welcome to come at https://gitter.im/OfflineIMAP/imapfw chat room to know more. ,-)
